### ISSUE TITLE
No more magic numbers

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#104]
Right now it seems like we have a bunch of values being hard-coded into our scripts. For example, I had to hunt through meshconfiguration.py to figure out what options we're passing to babeld, and presumable I would have to edit that file to make any changes to those options. All the hard-coded values should be pulled out into a configuration file instead of being buried somewhere in the source.

This is more of a best practice than a bug.

**Comment by virtadpt** [comment]
First step: Document everything that's hardcoded so we can start splitting it off into a config file.

babeld's command line options.

The command line options passed to the captive portal daemon.

Most of the command line options passed to the ccaptive portal shell script when it's used to initialize IP tables on the node.  Modulo those that are generated by the control panel, that is.

Come to think of it, we should revisit the command line options passed to babeld because some new features have been added recently.

**Comment by shanel** [comment]
Maybe skipping config files and just going with extensive command line flags might make sense?

**Comment by virtadpt** [comment]
If you mean the control panel, we could or we could not.  I followed the examples on the CherryPy website when I wrote the control panel.  If it would make things easier in the long run to hardcode the stuff in /etc/captiveportal/captiveportal.ini I'm fine with that.  It's not supposed to be user-configurable, anyway.  If you mean babeld, it's a lot easier to put an /etc/babeld.conf in because it gets awkward passing those options on the command line.

**Comment by shanel** [comment]
I'd suggest we move stuff into config files then.

**Comment by virtadpt** [comment]
This should go in the wiki as a best practice for developers.  This also occurs in too many places for just one ticket to be useful.

**Comment by Sitwon** [comment]
https://github.com/Byzantium/Byzantium/wiki/Development-Best-Practices
