### ISSUE TITLE
Network interfaces should be configured by default

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#126]
The purpose of Byzantium Linux is to turn a computer into a mesh router/gateway. The idea is to make it as easy to setup and configure as an off-the-shelf consumer broadband router. Therefore, we should make the experience a bit more like a COTS broadband router.

When Byzantium Linux boots up it should automatically detect the wireless interfaces and configure the first wireless interface for the mesh using the default settings. It should also try to configure any non-wireless interfaces using DHCP and propagate any new routes it discovers. 

The user can go into the control panel and make manual changes if they need to.

**Comment by virtadpt** [comment]
libdaemon and ifplugd have been re-added to the module repository for this purpose.  Autoconfiguration of wireless interfaces is on the roadmap for v0.3a but the control panel refactoring effort has to be finished first.

The nice thing about this is that it'll likely mean that code will have to be cut out rather than added.

**Comment by virtadpt** [comment]
Implemented by https://github.com/Byzantium/Byzantium/blob/master/byzantium_configd.py
