### ISSUE TITLE
Firefox What's New tab fix

### ISSUE THREAD

**Issue by hornc** [Byzantium/Byzantium#133]
replacing  line 36 in /porteus/home/guest/.mozilla/firefox/c3pp43bg.default/prefs.js
with:
user_pref("browser.startup.homepage_override.mstone", "ignore");

should get rid of the annoying what's new tab, showing the Byzantium config page directly.

I tested this by booting the live CD (byzantium-0.2a-20120627-2142.iso) and editing guest's prefs.js before loading firefox and it worked.

There is probably another way by updating version strings in te same file, but updating just lastAppVersion to 9.0.1 gave me a tab from the FlashGot AddOn.   The "ignore" above seems to catches everything, although it'll now never show a what's new if the browser is updated. Probably not a big deal for a live CD though?

**Comment by virtadpt** [comment]
It might be.  People can be finicky about the user experience: Even a harmless error can turn them off to what they're using because it gives the perception that the stuff under the hood is causing it.  You can't always tell what's cosmetic and what's not.

Added to repo and pushed in commit dcea250cc7e400f1271c20e03279627899f58090.

**Comment by hornc** [comment]
I've tested this and there are no longer extra firefox tabs when  the control panel is first opened in the latest isos.
