### ISSUE TITLE
/sbin not in terminal path, can't find lspci and other commands

### ISSUE THREAD

**Issue by hornc** [Byzantium/Byzantium#136]
/sbin  is not in $PATH so I can't use lspci as normal.. neither is /usr/sbin and probably others

ifconfig isn't found either and so on...

workaround: use full path names or cd directly to /sbin

Using  byzantium-0.2a-RC-20120628-2327.iso   WITHOUT copy2ram option  (I forgot to test this with the option enabled...  I'll update later)

**Comment by virtadpt** [comment]
$PATH before sudo: /usr/local/bin:/usr/bin:/bin:/usr/games:/opt/porteus-scripts:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/lib/qt/bin:.:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/lib/qt/bin:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/lib/qt/bin

There's lots of duplication there.  Too much.

$PATH after sudo: /usr/local/bin:/usr/bin:/bin:/usr/games:/opt/porteus-scripts:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/lib/qt/bin:.:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/lib/qt/bin:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/lib/qt/bin:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/kerberos/sbin:/usr/lib/qt/bin

The CWD is in the default path - bletch!  Gotta fix that.

Okay, this is something of a dog's breakfast.  Here are the default paths set in /etc/login.defs:

ENV_SUPATH=/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin
ENV_PATH=/usr/local/bin:/bin:/usr/bin

/etc/profile.d/*.sh makes life difficult for everyone.

Added /sbin to the default $PATH in commit 5bbfe56d24e0ef39d241cf89a87352e27d4513ba.

**Comment by virtadpt** [comment]
This seems to be a result of using sudo rather than su.

Value of $PATH after su: /usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/games:/opt/porteus-scripts:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/kerberos/sbin:/usr/lib/qt/bin:/usr/lib/java/bin:/usr/lib/java/jre/bin:/usr/kerberos/bin:/usr/kerberos/sbin:/usr/lib/qt/bin

This makes a good argument for unlocking the root account.  Or, we can just deal with it because it doesn't actually break anything.  But, that commit closes this ticket.
