### ISSUE TITLE
add documentation for submitting psinfo without persistent storage

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#167]
add documentation where appropriate (wiki, in distro docs, etc) to explain how to submit psinfo output without any persistent storage.

problems to address:
- can't write to normally rw media (permissions?)
- don't have writable media
- any/all the above without internet or mesh network, with and without the ability for clients to connect.

**Comment by starbits** [comment]
I am not sure why I cannot write to the USB (or to the laptop hard drive for that matter)  both are visible in PCMan, and I can read files on both, I only get permission errors when I try to write.  

One thing I thought of trying was to make the psinfo.txt file into a web page, because I can see the laptop's web page on my meshed iPad.  Once the page is on my iPad, I can copy and paste the text into an email or something.  I can edit psinfo.txt to make psinfo.html, but then I will need to move it into the /htdocs folder and I will need the url for the new page, to enter into my iPad.  A little help with those two things, and I will be able to get you your debugging info.

**Comment by haxwithaxe** [comment]
did you use the instructions for installing to usb that were on the iso? if you did, did you use ext3 or fat for the filesystem?

**Comment by starbits** [comment]
Umm, no, I did not follow instructions on installing the iso on USB.  I did not need to create a bootable thumb drive  because I had one of your CDs, and I used that.  The only instructions I found were on the wiki:
https://github.com/Byzantium/Byzantium/wiki/Helping-Test-Byzantium 
and they did not mention needing to mount the USB.  I am (obviously) not as familiar with linux as I should be and am sorry to give you such problems.

**Comment by virtadpt** [comment]
When another USB key is plugged into Porteus v2.0, a window shows up in the tray when the drive is detected.  It's not automounted.

System Tools -> Mount Drives -> <root password> -> Storage tab -> select drive -> check open folder -> Mount

Wiki page updated with a process I just used on a test node.
