### ISSUE TITLE
Byzantium V0.2a Network subnet issue

### ISSUE THREAD

**Issue by ghost** [Byzantium/Byzantium#171]
Hi,

I just signed up and found a few bugs, so here's my first one.

In the control panel, when you setup the networking, it states on the client IP is 10.x.x.x/24

But when this is finished and you go to ifconfig in the terminal, the client IP subnet mask is different:
WLAN0:1 10.x.x.x/8

One says the subnet mask is /24 in the control panel, but the ifconfig command says /8

255.255.255.0 = /24
255.0.0.0 = /8

The other address's subnet mask is correct.

Thanks
Scott

**Comment by haxwithaxe** [comment]
the ip for the client interface is in fact a /8 but the client only gets a /24 netmask because it can only address hosts within the /24 without talking to the mesh node. within the mesh it's irrelevant what the netmask is since routes are one to one. we were just being lazy and leaving the default /8 on the client interface.
definitely needs to be fixed but it doesn't break anything so far as we've seen.

**Comment by virtadpt** [comment]
It was a bit more than being lazy, it helps solve the problem of a mesh client drifting into range of another mesh node and having to wait for its DHCP lease to expire before it could send traffic.  By using a netmask of /8 on the mesh interface, clients will hit the captive portal immediately (and then get a new DHCP lease shortly therafter) rather than broadcast packets with nothing able to recieve and respond to them until the lease is up.
