### ISSUE TITLE
Retroshare package

### ISSUE THREAD

**Issue by AEtherC0r3** [Byzantium/Byzantium#200]
Hi,
Retroshare is open source and can be used for secure & decentralized communications
so it would be great if you could include it in Byzantium linux.
More info : http://retroshare.sourceforge.net

**Comment by virtadpt** [comment]
Retroshare is also one user per node, and our use case is multiple users per node across lots of nodes.  I'm not sure Retroshare is a good fit.

**Comment by ghost** [comment]
Nice idea, having a P2P software in here. 
http://www.osiris-sps.org/download/ 
Anybody used this one?

Maybe when Byzantium gets to version One, have a P2P installed in it.

**Comment by jbshirk** [comment]
I have set it up but not 'used' it as i had trouble finding friends (just like retroshare). i'd say it works very well, its design is good, although the dox are italian-centric and the 90's-ish spaceship video game control panel theme seems kind of juvenile to me.

**Comment by virtadpt** [comment]
I've had my eye on Osiris and Isis for a while, but the last release was back in 2011.

**Comment by virtadpt** [comment]
Hopefully Groundstation will do what you're asking.

**Comment by virtadpt** [comment]
Closing because Retroshare isn't a good fit for Byzantium:
- Requires additional key management on the part of users
  *\* Generate a PGP key.
  *\* Set a passphrase on it.
  *\* Log into Retroshare by unlocking PGP key.
- Desktop only - the HTTPS interfaces to retroshare-nogui haven't been toucned in months or years.
- Requires that users exchange public keys and manage personal webs of trust.

These are non-starters in emergency situations, even though Retroshare has some useful features (like fairly decent VoIP and distributed chat forums).  Some of those features are implemented in other apps.
