### ISSUE TITLE
is there a 64-bit ISO version?

### ISSUE THREAD

**Issue by jbshirk** [Byzantium/Byzantium#202]
I intend to install on a macbook pro, which is 64 bits. I noted that Porteus linux comes in 32 and 64 bit versions. Which is in http://project-byzantium.org/download/ ?

**Comment by Sitwon** [comment]
Hi jbshirk,

64-bit x86 processors (like the Intel CPU inside a Macbook Pro) can run
both 64-bit an 32-bit code. Many of the systems we develop and test on have
similar 64-bit processors. We chose to develop for 32-bit only because it
is the more generic platform. As one of our design features is the ability
to replicate it's important that we keep the OS as generic as possible.

Up to this point we have had some challenges with getting Byzantium to work
on MacBooks, however our next milestone for the ISC Grant will be to solve
those challenges. This is one of the most requested features.

Best regards,
Ben the Pyrate

**Comment by virtadpt** [comment]
We're now building and testing RC's (release candidates) of the Mac port of Byzantium as part of grant milestone #2.

To facilitate getting things out the door for this milestone (as well as making .iso images compatible with both Macs and PCs) we're only publishing 32-bit images.  That can and probably will change in the future but we're on a pretty strict development schedule.

The process for actually making a 64-bit port would be much the same as the process for the 32-bit port - make a fakeroot, populate the fakeroot, unpack all of the packages into it, dir2xzm, remaster the .iso.

**Comment by haxwithaxe** [comment]
Until 32bit x86 machines are hard to find we will only publish 32bit ISOs and images. Nothing we have is inherently 32bit but for the purposes of reduced confusion in the field we will only publish 32bit for now.
I'm closing this ticket. We apreciate your feedback and question. Please keep them coming :)

**Comment by Sitwon** [comment]
Hmm, this sounds familiar...

http://hackaday.com/2014/05/01/airchat-the-wireless-mesh-network-from-lulzlabs/

**Comment by virtadpt** [comment]
Indeed.
I read through the source code a few nights ago.  It's written in Perl and does pretty much the same thing as Groundstation, though it doesn't seem to concern itself with congestion management, nor can it be used with anything other than fldigi.  It's not TCP/IP aware, but packet radio-only.
