### ISSUE TITLE
Can't start SSH via control_panel

### ISSUE THREAD

**Issue by Sitwon** [Byzantium/Byzantium#47]
Permission denied, because /etc/rc.d/rc.sshd is not +x.

**Comment by virtadpt** [comment]
rc.sshd is part of Porteus Linux - it's not ours and it's not on by default.

We will have to check Porteus' /etc/rc.d/rc.M initscript into Git so that we have control over it because we'll have to comment out the lines that test for the execute bit on /etc/rc.d/rc.sshd and run it if it's set.  That's standard functionality in Slackware (and hence Porteus).

How do we want to set up the tree in Git for scripts that we'll have to handle ourselves?  I'm thinking something like this:

```
 Byzantium/porteus/native/
```

for scripts that came from Porteus, and then we put whatever we're handling ourselves under that directory tree where it would go on the live system.  So, in this case, we'd have:

```
 Byzantium/porteus/native/etc/rc.d/rc.M
```

In the long run, this might also make it easier to manage the initscripts for stuff we package ourselves because we'd have a single location in the repository to copy stuff from, rather than hunting all over the Git repo for initscripts that might be forgotten.  Sound reasonable?

**Comment by virtadpt** [comment]
The fix to this was remarkably easy: rc.sshd is set +x by rc.local after everything else is said and done.  It also stops a few things and sets their initscripts -x.
