### ISSUE TITLE
multiple errors from boot onward via skyl4rk

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#80]
This was done with the second iso after fixes.

Dell Latitude D830, x86, 32bit, 2GB memory
Alfa UBDo-nt outdoor usb cpe 802.11 n/b/g (wireless antenna)

Byzantium cd boot graphical mode (no options)
shell error message: dnsmasq...cannot read dnsmasq.conf file (or
similar)
boots into kde with error alert box: klauncher said: unable to create
io-slave
firefox with localhost:8080
configure network interfaces - wlan1 configured
mesh routing enabled
Byzantium appears as a wireless network on other pc (Ubuntu netbook)
Does not appear on cell phone
Not able to connect from netbook
Enabled web chat
Turn on eth0 as gateway
iwlist scan, Byzantium appears
Not able to connect
iwconfig on Byzantium pc, Byzantium is an Ad-Hoc network (should be
Master?)
Not able to connect to Byzantium.
My Ubuntu netbook network connection is sometimes flaky, not sure if
problem is there
Noticed that etc/captiveportal.conf points to srv/captiveportal, which
contains index.html.en-us
Perhaps must lose .en-us extension?

**Comment by haxwithaxe** [comment]
from my email reply:

> Byzantium appears as a wireless network on other pc (Ubuntu netbook)
> Does not appear on cell phone
> this may be due to an unusually large number of smart phones having chipsets that don't support adhoc mode. what model is the phone? 
> iwconfig on Byzantium pc, Byzantium is an Ad-Hoc network (should be
> Master?)
> it's supposed to be adhoc. the wireless mesh part of the system requires it and most wifi cards in non-router devices don't support running master mode.
> Not able to connect to Byzantium.
> were you using the default network manager or wicd?
> wicd has issues connecting to adhoc networks.
> My Ubuntu netbook network connection is sometimes flaky, not sure if
> problem is there
> join the club :P always a possibility but it might be something else too.
> Noticed that etc/captiveportal.conf points to srv/captiveportal, which
> contains index.html.en-us
> Perhaps must lose .en-us extension?
> that's just for serving up the captive portal pages in different languages. it doesn't effect the network connectivity.

**Comment by virtadpt** [comment]
A few people have reported the errors (which are harmless) at boot-time as problematic.  The user experience is that they don't know if things are okay with the node or not, and that could lead to problems farther down the line (a perception of unreliability or an unwillingness to fix reported bugs).  Not good.  This includes things like dnsmasqd reporting that a config file is missing (when it hasn't been created yet by the control panel).

We have a couple of options.  For certain services we can not start them at boot-time because we assume that the node hasn't been configured at all whenever it boots, and in fact a node will probe for new configuration settings every time it comes up.  So, it might make sense to not bother starting them from the initscripts; the control panel will configure and start them anyway.  These services include Apache (it can't find its SSL cert because it hasn't been created yet; this happens elsewhere in the Porteus initscript system), dnsmasqd, and possibly traffic_stats.sh.

Another option, for the services that have to start, anyway, is to redirect stderr to /dev/null.  For harmless errors, this is again not a big deal.

**Comment by virtadpt** [comment]
Removed rc.dnsmasq from rc.local so it won't try to start at boot-time.  It won't start properly until the control panel finishes configuring it.

**Comment by virtadpt** [comment]
c.f. commit d2a66628d3b71d09d5dac58455cf3a2b0ce926f8.

**Comment by virtadpt** [comment]
Tests in a live environment successful.
