### ISSUE TITLE
Clean up the merge of Byzantium and Porteus.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#84]
There are a number of scripts and associated files used by the Porteus Linux installer to verify integrity and keep everything straight.  I haven't had a chance to sit down and figure it out yet, but this is going to be relevant for the installation (see ticket #79) and cloning-during-runtime scripts.  I'll put my notes here as I figure things out.

**Comment by Sitwon** [comment]
Are you referring to the md5sums.txt file which checks the integrity of the core Porteus modules? We _could_ add the MD5 sums for the Byzantium modules to this list before each release so that they get checked whenever someone makes a copy of Byzantium Linux.

The issue in ticket #79 is solved so without a more specific problem statement I'm not sure I can't act on this ticket. There doesn't seem to be anything else to "fix" here.

**Comment by virtadpt** [comment]
I am referring to that, yes.

Let's do that.  It'll help in the long run.

Also, we should edit the boot loader config files and /etc/motd to reflect Byzantium Linux rather than Porteus Linux (while giving Porteus proper credit).  It's fairly simple but more fiddly stuff has been in the queue lately.  We really should do it (and check the files into Git) for v0.2a.

**Comment by virtadpt** [comment]
Everything talked about in this ticket has become part of the build process for the .iso images in remaster_iso.sh.
